[theme]
primaryColor = "#FFD700"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1e2130"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
enableCORS = false
port = 8501

[browser]
gatherUsageStats = false
